// export const CREATE_CONTACT = "CREATE_CONTACT"s
export const ADD_CONTACT = "ADD_CONTACT";
export const RETRIEVE_CONTACTS = "RETRIEVE_CONTACTS";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const MAKE_AUTHENTICATED = "MAKE_AUTHENTICATED";
export const MAKE_UNAUTHENTICATED = "MAKE_UNAUTHENTICATED";
export const CHANGE_FAVOURITE = "CHANGE_FAVOURITE";